// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArUd0Heke5SKGOHB84oFR-Opap9Grf4do',
    appId: '1:272202532312:web:8e09e2438af5d8b306dead',
    messagingSenderId: '272202532312',
    projectId: 'ai-assistant-ea8f1',
    authDomain: 'ai-assistant-ea8f1.firebaseapp.com',
    storageBucket: 'ai-assistant-ea8f1.firebasestorage.app',
    measurementId: 'G-98PQKEL5V4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLHvh94RBdsgynK_DYMhw_VtkTyFJPVIs',
    appId: '1:272202532312:android:dc1ec5981d7916ad06dead',
    messagingSenderId: '272202532312',
    projectId: 'ai-assistant-ea8f1',
    storageBucket: 'ai-assistant-ea8f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjc2hAn7zt8092MYe26V4j7pGx5hCfAMQ',
    appId: '1:272202532312:ios:d9d08299a9c5a46506dead',
    messagingSenderId: '272202532312',
    projectId: 'ai-assistant-ea8f1',
    storageBucket: 'ai-assistant-ea8f1.firebasestorage.app',
    iosClientId: '272202532312-i3rs8ojf3giddrcbjrs4g1ltcqd576o4.apps.googleusercontent.com',
    iosBundleId: 'com.theinfamoustheta.aiAssistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjc2hAn7zt8092MYe26V4j7pGx5hCfAMQ',
    appId: '1:272202532312:ios:d9d08299a9c5a46506dead',
    messagingSenderId: '272202532312',
    projectId: 'ai-assistant-ea8f1',
    storageBucket: 'ai-assistant-ea8f1.firebasestorage.app',
    iosClientId: '272202532312-i3rs8ojf3giddrcbjrs4g1ltcqd576o4.apps.googleusercontent.com',
    iosBundleId: 'com.theinfamoustheta.aiAssistant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArUd0Heke5SKGOHB84oFR-Opap9Grf4do',
    appId: '1:272202532312:web:60d74be8255aa50906dead',
    messagingSenderId: '272202532312',
    projectId: 'ai-assistant-ea8f1',
    authDomain: 'ai-assistant-ea8f1.firebaseapp.com',
    storageBucket: 'ai-assistant-ea8f1.firebasestorage.app',
    measurementId: 'G-2N8HEXTBEY',
  );

}